export default [
  {
    athlete_id: 123,
    first_name: "New User",
    totalPrice: 0,
    totalDiamond: 0,
    letterSound: [
      {
        id: 1,
        soundColor: require(`../assets/sound/red.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/red.png"),
        buy: true,
        count: 1,
        price: 0,
      },
      {
        id: 2,
        soundColor: require(`../assets/sound/green.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/green.png"),
        buy: true,
        count: 1,
        price: 5,
      },
      {
        id: 3,
        soundColor: require(`../assets/sound/pink.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/pink.png"),
        buy: false,
        count: 1,
        price: 10,
      },
      {
        id: 4,
        soundColor: require(`../assets/sound/yellow.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/yellow.png"),
        buy: false,
        count: 1,
        price: 20,
      },
      {
        id: 5,
        soundColor: require(`../assets/sound/orange.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/orange.png"),
        buy: false,
        count: 1,
        price: 30,
      },
      {
        id: 6,
        soundColor: require(`../assets/sound/blue.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/blue.png"),
        buy: false,
        count: 1,
        price: 40,
      },
      {
        id: 7,
        soundColor: require(`../assets/sound/brown.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/brown.png"),
        buy: false,
        count: 1,
        price: 45,
      },
      {
        id: 8,
        soundColor: require(`../assets/sound/purple.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/purple.png"),
        buy: false,
        count: 1,
        price: 50,
      },
    ],
  },
];
