export default [
  {
    athlete_id: 123,
    first_name: "New User",
    totalPrice: 0,
    totalDiamond: 0,
    letterSound: [
      {
        id: 0,
        soundShaps: require(`../assets/sound/circle.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/circle.png"),
        buy: true,
        count: 1,
        price: 0,
      },
      {
        id: 1,
        soundShaps: require(`../assets/sound/diamond.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/diamond.png"),
        buy: false,
        count: 1,
        price: 0,
      },
      {
        id: 2,
        soundShaps: require(`../assets/sound/Square.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/squ.png"),
        buy: false,
        count: 1,
        price: 5,
      },
      {
        id: 3,
        soundShaps: require(`../assets/sound/oval.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/oval.png"),
        buy: false,
        count: 1,
        price: 10,
      },
      {
        id: 4,
        soundShaps: require(`../assets/sound/triangle.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/tri.png"),
        buy: true,
        count: 1,
        price: 20,
      },
      {
        id: 5,
        soundShaps: require(`../assets/sound/rectangle.mp3`),
        unLockSound: require("../assets/sound/Kids_Cheering.mp3"),
        img: require("../assets/images/rect.png"),
        buy: false,
        count: 1,
        price: 30,
      },
    ],
  },
];
